### ISSUE TITLE
Overlay layer on Sway

### ISSUE THREAD

**Issue by nothingelsematters** [Leon-Plickat/LavaLauncher#1]
While tweaking the configuration file on Sway WM, I have the following performance with `layer` property:  
`background`: nothing appears on the screen but it works, it will expand on hover (an empty gap at the bottom appears) and buttons magically work as well  
`top`, `bottom` and `overlay` are the same: it works fine and it moves the window located on the screen higher while expanding

I suppose that `top` and `overlay` should be seen upon the windows and not move them, this is based on the documentation:
> Typically, "bottom" and "background" will be underneath regular windows, while "top" and "overlay" will be above them

Is this a bug, or have I just misunderstood the manual?

> Package versions:
>
> ```
> sway         version: 1.5
> lavalauncher version: 2.0.0
> ```

**Comment by Leon-Plickat** [comment]
On Fri Oct 16, 2020 at 1:28 PM CEST, Simon Naumov wrote:
> While tweaking the configuration file on Sway WM, I have the following
> performance with `layer` property:
> `background`: nothing appears on the screen but it works, it will expand
> on hover (an empty gap at the bottom appears) and buttons magically work
> as well

The wallpaper in sway is rendered by swaybg, which also uses the layer
shell on background layer. For some odd reason, layer shell clients in
sway are rendered in order of appearance, meaning lavalauncher will be
"behind" swaybg if it is launched after it. You can still interact
with LavaLauncher because swaybg tells sway that it does not want to
receive any input events, so your mouse clicks just pass through.

> `top`, `bottom` and `overlay` are the same: it works fine and it moves
> the window located on the screen higher while expanding
>
> I suppose that `top` and `overlay` should be seen upon the windows and
> not move them

This has nothing to do with the layer, but with the exclusive zone.
Set `exclusive-zone` to `false` or `stationary` and sway will no
longer move windows out of the way when LavaLauncher is expanding.

Layer _only_ controls whether LavaLauncher is above or below other
things (as such you probably want to set the layer to `top` when using
hiding with disabled exclusive zone).


Friendly greetings,
Leon Plickat

**Comment by nothingelsematters** [comment]
Oh, I see now, thanks a lot!
