### ISSUE TITLE
Error when starting LavaLauncher

### ISSUE THREAD

**Issue by RicArch97** [Leon-Plickat/LavaLauncher#4]
Updated to v2.1.0 via the AUR, adjusted config accordingly.

```
global-settings 
{
        watch-config-file = true;
}

bar 
{
        # Bar on right monitor
        output = DP-2;
        size = 52;
        position = left;
        margin = 10;
        border = 0;
        background-colour = "#00000000";
        alignment = center;
        exclusive-zone = false;
        indicator-style = circle;
        cursor-name = wayland-cursor;
        mode = default;

        config
        {       
                # Bar on left monitor
                output = HDMI-A-1;
                icon-padding = 8;
        }

        button 
        {       
                image-path = /usr/share/icons/McMojave-circle-grey-dark/apps/scalable/vscode.svg;
                command = code;
        }

        spacer 
        {
                length = 4;
        }

        <and more buttons and spacers>
}
```

Running gives the following error:
```
wl_registry@2: error 0: invalid version for global zwlr_layer_shell_v1 (12): have 2, wanted 4
ERROR: wl_display_dispatch: Protocol error
```
I'm using Sway version 1.5.1

**Comment by Leon-Plickat** [comment]
On Mon Apr 12, 2021 at 4:34 PM CEST, Ricardo Steijn wrote:
> I'm using Sway version 1.5.1

There is your problem. The new LavaLauncher version has an updated
LayerShell version, but Sway 1.5.1 does not support that yet.

You need to either downgrade LavaLauncher or uprade Sway to 1.6.

To my knowledge there isn't any (good) way of supporting both versions
of the protocol, because some major changes relating to keyboard input.


Friendly greetings,
Leon Henrik Plickat

**Comment by RicArch97** [comment]
Thanks for your response.

It seems like Sway 1.6 was released 5 days ago, but still lives in `community-staging` in the AUR. I will build Sway 1.6 and test again.

Following up on the AUR, my helper hints that there's an update for LavaLauncher:
```
1. lavalauncher: 2.1.0-0 ==> 2.1.0-1
```
However the package seems to be identical:
```
warning: lavalauncher-2.1.0-0 is up to date -- reinstalling
```

**Comment by Leon-Plickat** [comment]
On Mon Apr 12, 2021 at 11:03 PM CEST, Ricardo Steijn wrote:
> Following up on the AUR, my helper hints that there's an update for
> LavaLauncher:
> ```
> 1. lavalauncher: 2.1.0-0 ==> 2.1.0-1
> ```
> However the package seems to be identical:
> ```
> warning: lavalauncher-2.1.0-0 is up to date -- reinstalling
> ```

Yeah that is a typo in the `.SRCINFO` file, thanks for reporting.

It's a somewhat common AUR mistake, because both `.SRCINFO` and
`PKGBUILD` contains basically the same meta information and they have
to match.

I'll fix it in a minute.



Friendly greetings,
Leon Henrik Plickat
